install:
  - docker-compose -f docker-compose_test.yml build test
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - docker-compose -f docker-compose_test.yml run --name newsgac_test test
after_script:
  - docker cp newsgac_test:/newsgac/coverage.xml ./coverage_docker.xml
  - docker-compose -f docker-compose_test.yml down
  - cat coverage_docker.xml | sed "s|<source>.*</source>|<source>newsgac</source>|" > coverage.xml
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT --debug
