image: docker:stable

pipelines:
  default:
    - step:
        services:
          - docker
        caches:
          - docker
        script:
          - chmod a+x ci/dependencies.sh
          - ci/dependencies.sh
          - docker-compose -f docker-compose.yml -f docker-compose_test.yml build test
          - docker-compose -f docker-compose.yml -f docker-compose_test.yml run test
          - docker-compose -f docker-compose.yml -f docker-compose_test.yml down
definitions:
  services:
    docker:
      memory: 3072