version: "3"

networks:
    newsgac-net:
        driver: bridge

services:
    frog:
        hostname: proycon/lamachine
        image: proycon/lamachine:latest
        command: bash -c "frog -S 12345"
        networks:
            - newsgac-net

    redis:
        hostname: redis
        image: redis:latest
#        environment:
#            - redisMQ_DEFAULT_USER=newsgac
#            - redisMQ_DEFAULT_PASS=1234
        restart: on-failure
#        volumes:
#            - ../redismq:/var/lib/redismq
        networks:
            - newsgac-net

    worker:
        build:
            context: ./newsgac
            dockerfile: Dockerfile_celery
        links:
            - redis
            - database
            - frog
        depends_on:
            - redis
            - database
            - frog
        restart: on-failure
        networks:
            - newsgac-net

    flower:
        image: mher/flower:latest
        volumes:
            - ./newsgac:/newsgac
        links:
            - redis

    database:
        hostname: mongo
        image: mongo:latest
        networks:
            - newsgac-net

    web:
        build:
            context: ./newsgac
            dockerfile: Dockerfile_flask
        links:
            - worker
            - redis
            - database
            - frog
        depends_on:
            - database
            - worker
            - frog
        restart: on-failure
        networks:
            - newsgac-net
            
volumes:
    redismq:
