version: "3"

services:
    frog:
        env_file:
            - .env.prod

    redis:
        env_file:
            - .env.prod

    database:
        env_file:
            - .env.prod
        volumes:
            - /export/scratch2/home/aysenur/newsgac_db/:/data/db

    worker:
        env_file:
            - .env.prod
        command: celery -A newsgac.tasks.celery_app worker -l warning --concurrency 40 -n worker@%h


    frogworker:
        env_file:
        - .env.prod
        command: celery -A newsgac.tasks.celery_app worker -l warning --concurrency 6 -n frogworker@%h -Q frog


    web:
        env_file:
            - .env.prod

    nginx:
        build:
            context: nginx
            dockerfile: Dockerfile
        image: newsgac/nginx
        depends_on:
            - web
            - jupyterhub
        restart: on-failure
        networks:
            newsgac-net:
                aliases:
                    - nginx
                    - http
        ports:
            - "5050:80"


    jupyterhub:
        build:
            context: .
            dockerfile: jupyter/Dockerfile
        image: newsgac/jupyterhub
        volumes:
            - /export/scratch2/home/aysenur/hub_notebooks:/notebooks
        depends_on:
            - redis
            - database
            - worker
            - frog
        restart: on-failure
        networks:
            - newsgac-net
        env_file:
            - .env.prod

    ngrok:
        networks:
            - newsgac-net
        depends_on:
            - nginx
        image: wernight/ngrok
        env_file:
            - .env.prod
