version: "3"

services:
    frog:
        ports:
            - "12345:12345"
        env_file:
            - .env.localdocker

    redis:
        ports:
            - "6379:6379"
            - "6380:6380"
        env_file:
            - .env.localdocker

    database:
        ports:
            - "27017:27017"
        env_file:
            - .env.localdocker
        volumes:
            - ./../data:/data/db

    worker: &worker-base
        hostname: celeryworker
        volumes:
            - ./newsgac:/newsgac/newsgac
        env_file:
            - .env.localdocker
        command: ["sh", "-c", "pip install watchdog && watchmedo auto-restart --patterns=\"*.py\" --recursive -- celery -A newsgac.tasks.celery_app worker -l info --concurrency 1 -n worker1@%h" ]

    frogworker:
        <<: *worker-base
        command: celery -A newsgac.tasks.celery_app worker -l info --concurrency 2 -n frogworker@%h -Q frog

    web:
        volumes:
            - ./newsgac:/newsgac/newsgac
        ports:
            - "5050:5050"
        env_file:
            - .env.localdocker
        command: ["python", "newsgac/app.py"]
        environment:
            - PYTHONPATH=/newsgac

    ws-celery-monitor:
        ports:
            - "5051:5051"
