version: "3"

services:
    frog:
        env_file:
            - .env.prod

    rabbit:
        env_file:
            - .env.prod

    database:
        env_file:
            - .env.prod

    worker:
        env_file:
            - .env.prod

    web:
        env_file:
            - .env.prod
        ports:
            - "5000:5000"

