version: "3"

networks:
    newsgac-net:
        driver: bridge

services:
    frog:
        hostname: proycon/lamachine
        image: proycon/lamachine:latest
        command: bash -c "frog -S 12345"
        networks:
            - newsgac-net

    redis:
        hostname: redis
        image: redis:latest
        restart: on-failure
        networks:
            - newsgac-net

    database:
        hostname: mongo
        image: mongo:latest
        networks:
            - newsgac-net

    web:
        build:
            context: .
            dockerfile: Dockerfile
        image: newsgac/web
        links:
            - worker
            - redis
            - database
            - frog
        depends_on:
            - database
            - worker
            - frog
        restart: on-failure
        networks:
            - newsgac-net
        command: ["gunicorn", "--workers", "10", "--max-requests", "10", "--timeout", "80", "--bind", "0.0.0.0:5050", "--access-logfile", "-", "--error-logfile", "-", "newsgac.app:app"]

    worker: &worker-base
        build:
            context: .
            dockerfile: Dockerfile
        image: newsgac/worker
        depends_on:
            - redis
            - database
        restart: on-failure
        networks:
            - newsgac-net
        command: celery -A newsgac.tasks.celery_app worker -l warning --concurrency 10 -n worker@%h

    frogworker:
        <<: *worker-base
        image: newsgac/frogworker
        depends_on:
            - redis
            - database
            - frog
        command: celery -A newsgac.tasks.celery_app worker -l warning --concurrency 2 -n frogworker@%h -Q frog
