version: "3"

services:
    frog:
        ports:
            - "12345:12345"
        env_file:
            - .env.localdocker

    redis:
        ports:
            - "6379:6379"
            - "6380:6380"
        env_file:
            - .env.localdocker

    database:
        ports:
            - "27017:27017"
        env_file:
            - .env.localdocker
        volumes:
            - ./../data:/data/db

    worker:
        hostname: celeryworker
        volumes:
            - ./newsgac:/newsgac
        env_file:
            - .env.localdocker
        command: ["sh", "-c", "pip install watchdog && watchmedo auto-restart --patterns=\"*.py\" --recursive -- celery -A celery_tasks.celery_app worker -l info --concurrency 1 -n worker1@%h" ]

    flower:
        ports:
          - "5555:5555"
        entrypoint: ["sh", "-c", "cd /newsgac && ls && celery flower --broker=amqp://newsgac:1234@localhost:5672/"]

    web:
        volumes:
            - ./newsgac:/newsgac
        ports:
            - "5000:5000"
        env_file:
            - .env.localdocker
