version: "3.2"

services:
    jupyterhub:
        build:
            context: .
            dockerfile: jupyter/Dockerfile
        image: newsgac/jupyterhub
        volumes:
            - ${JUPYTER_NOTEBOOK_DIRECTORY}:/notebooks
        depends_on:
            - redis
            - database
            - worker
            - frog
        env_file:
            - .env.prod
        deploy:
            restart_policy:
                condition: on-failure
                delay: 10s
                max_attempts: 3
            replicas: 1

    worker:
        command: "celery -A newsgac.tasks.celery_app worker -l warning --concurrency 10 -n worker@%h"


    nginx:
        build:
            context: nginx
            dockerfile: Dockerfile
        image: newsgac/nginx
        depends_on:
            - web
            - jupyterhub
        deploy:
            replicas: 1
            restart_policy:
                condition: on-failure
                delay: 10s
                max_attempts: 3
        ports:
        - target: 80
          published: 5055
          protocol: tcp
          mode: host



    ngrok:
        depends_on:
            - nginx
        image: wernight/ngrok
        deploy:
            replicas: 1
            restart_policy:
                condition: any
                delay: 10s
                max_attempts: 3
