version: "3"

services:
    frog:
        env_file:
            - .env.prod

    rabbit:
        env_file:
            - .env.prod

    database:
        env_file:
            - .env.prod
        volumes:
            - export/scratch2/home/aysenur/newsgac_db/:/data/db

    worker:
        env_file:
            - .env.prod

    web:
        env_file:
            - .env.prod
        ports:
            - "5000:5000"
        command: ["gunicorn", "--workers", "10", "--max-requests", "10", "--timeout", "30", "--bind", "0.0.0.0:5000", "--access-logfile", "-", "--error-logfile", "-", "app:app"]


