version: "3"

services:
    frog:
        env_file:
            - .env.dockertest
        restart: "no"

    redis:
        env_file:
            - .env.dockertest
        restart: "no"

    database:
        env_file:
            - .env.dockertest
        volumes:
            - ./../data:/data/db
        restart: "no"

    worker:
        entrypoint: ["/bin/true"]

    frogworker:
        entrypoint: ["/bin/true"]

    web:
        entrypoint: ["/bin/true"]

    test:
        env_file:
            - .env.dockertest
        build:
            context: .
            dockerfile: Dockerfile
        image: newsgac/test
        depends_on:
            - database
            - frog
            - redis
        networks:
            - newsgac-net
        command: ["pytest", "."]