version: "3"

networks:
    newsgac-net:
        driver: bridge

services:
    database:
        hostname: mongo
        image: mongo:latest
        networks:
            - newsgac-net
        env_file:
            - .env.dockertest
        volumes:
            - ./data:/data/db
        restart: "no"

    test:
        env_file:
            - .env.dockertest
        build:
            context: .
            dockerfile: Dockerfile
        image: newsgac/test
        depends_on:
            - database
        networks:
            - newsgac-net
        entrypoint: /bin/sh -c
        command: ["pytest --cov=newsgac --cov-report=xml"]