version: "3"

services:
    frog:
        ports:
            - "12345:12345"
        env_file:
            - .env.localdocker

    rabbit:
        ports:
            - "4369:4369"
            - "5671:5671"
            - "5672:5672"
            - "5673:5673"
        env_file:
            - .env.localdocker

    database:
        ports:
            - "27017:27017"
        env_file:
            - .env.localdocker
        volumes:
            - ./../data:/data/db

    worker:
        volumes:
            - ./flask/src:/flask/src
        env_file:
            - .env.localdocker

    web:
        volumes:
            - ./flask/src:/flask/src
        ports:
            - "5000:5000"
        env_file:
            - .env.localdocker
