version: "3"

services:
    frog:
        env_file:
            - .env.prod

    redis:
        env_file:
            - .env.prod

    database:
        env_file:
            - .env.prod
        volumes:
            - ./../data:/data/db

    worker:
        env_file:
            - .env.prod

    web:
        env_file:
            - .env.prod
        ports:
            - "5000:5000"

    ws-celery-monitor:
        ports:
        - "8080:8080"