version: "3"

networks:
    newsgac-net:
        driver: bridge

services:
    frog:
        hostname: proycon/lamachine
        image: proycon/lamachine:latest
        command: bash -c "frog -S 12345"
        networks:
            - newsgac-net

    rabbit:
        hostname: rabbit
        image: rabbitmq:latest
        environment:
            - RABBITMQ_DEFAULT_USER=newsgac
            - RABBITMQ_DEFAULT_PASS=1234
        restart: on-failure
        networks:
            - newsgac-net

    worker:
        build:
            context: ./flask
            dockerfile: Dockerfile_celery
        links:
            - rabbit
            - database
            - frog
        depends_on:
            - rabbit
            - database
            - frog
        restart: on-failure
        networks:
            - newsgac-net

    database:
        hostname: mongo
        image: mongo:latest
        networks:
            - newsgac-net

    web:
        build:
            context: ./flask
            dockerfile: Dockerfile_flask
        links:
            - worker
            - rabbit
            - database
            - frog
        depends_on:
            - database
            - worker
            - frog
        restart: on-failure
        networks:
            - newsgac-net
            
