version: "3"

networks:
    newsgac-net:
        driver: bridge

services:
    frog:
        hostname: proycon/lamachine
        image: proycon/lamachine:latest
        ports:
            - "12345:12345"
        command: bash -c "frog -S 12345"
        networks:
            - newsgac-net

    rabbit:
        hostname: rabbit
        image: rabbitmq:latest
        environment:
            - RABBITMQ_DEFAULT_USER=newsgac
            - RABBITMQ_DEFAULT_PASS=1234
        ports:
            - "5672:5672"
        restart: on-failure
        networks:
            - newsgac-net
    
    worker:
        build:
            context: ./flask
            dockerfile: Dockerfile_celery
        links:
            - rabbit
            - database
            - frog
        depends_on:
            - rabbit
            - database
            - frog
        networks:
            - newsgac-net
        restart: on-failure
    
    database:
        hostname: mongo
        image: mongo:latest
        volumes:
            - /export/scratch2/home/aysenur/newsgac_db/:/data/db
        ports:
            - "27017:27017"
        networks:
            - newsgac-net
    
    web:
        build:
            context: ./flask
            dockerfile: Dockerfile_flask
        ports:
            - "5000:5000"
        links:
            - worker
            - rabbit
            - database
            - frog
        depends_on:
            - database
            - worker
            - frog
        networks:
            - newsgac-net
        restart: on-failure
            
