apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: database-claim0
  name: database-claim0
  namespace: tci-newsgac
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
